### PR TITLE
feat: add Swift modules and an iOS application

### PR DESCRIPTION
**Pull request by cgrindel**
### Type of change

Add Swift modules and an iOS application to the repository to demonstrate:
- Use of [rules_swift](https://github.com/bazelbuild/rules_swift) and [rules_apple](https://github.com/bazelbuild/rules_apple).
- Import of an external Swift package (e.g., [SwifterSwift](https://github.com/SwifterSwift/SwifterSwift)) using [rules_swift_package_manager](https://github.com/cgrindel/rules_swift_package_manager).
- Integration with Xcode using [rules_xcodeproj](https://github.com/MobileNativeFoundation/rules_xcodeproj).

Chores

- Update Bazel version to 6.3.2.
- Update Go dependencies to latest.
- Update Gazelle declaration to include Swift plugin.

### Test plan

- New test cases added

Unit tests can be run using `bazel test //...`. The UI tests for the iOS application can be run using `bazel test //ios/LoggingClient/UITests`.

### CODE REVIEW

**Review by alexeagle — APPROVED** [review]
Thanks!

**Comment by cgrindel** [comment]
@alexeagle I just updated the bazelrc to output more info about the UITest failure in CI. Could you approve the workflow?

**Comment by alexeagle** [comment]
I turned off that setting for now, I didn't mean to block your PRs on that approval!

**Comment by cgrindel** [comment]
I guess that UI test failure did not occur again. 🤷‍♂️

**Pull request merged**
